//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 01:02:18 PM CET 
//


package org.mitre.oval.xmlschema.oval_definitions_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The EntityStateIOSVersionType type is extended by the entities of an individual OVAL State. This type provides uniformity to each state entity by including the attributes found in the EntityStateSimpleBaseType. This specific type represents the version string related to CISCO IOS.
 * 
 * <p>Java class for EntityStateIOSVersionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityStateIOSVersionType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;restriction base="&lt;http://oval.mitre.org/XMLSchema/oval-definitions-5&gt;EntityStateSimpleBaseType"&gt;
 *       &lt;attribute name="datatype"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://oval.mitre.org/XMLSchema/oval-common-5}SimpleDatatypeEnumeration"&gt;
 *             &lt;enumeration value="ios_version"/&gt;
 *             &lt;enumeration value="string"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityStateIOSVersionType", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5")
public class EntityStateIOSVersionType
    extends EntityStateSimpleBaseType
{


}
