//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 01:02:18 PM CET 
//


package org.mitre.oval.xmlschema.oval_definitions_5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.mitre.oval.xmlschema.oval_common_5.CheckEnumeration;


/**
 * The entity_check and var_check attributes are considered together when evaluating a single state entity. When a variable identifies more than one value and multiple item entities with the same name exist, for a single state entity, a many-to-many comparison must be conducted.  In this situation, there are many values for the state entity that must be compared to many item entities.  Each item entity is compared to the state entity. For each item entity, an interim result is calculated by using the var_check attribute to combine the result of comparing each variable value with a single system value. Then these interim results are combined for each system value using the entity_check attribute.
 * 
 * <p>Java class for EntityStateComplexBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityStateComplexBaseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://oval.mitre.org/XMLSchema/oval-definitions-5}EntityComplexBaseType"&gt;
 *       &lt;attribute name="entity_check" type="{http://oval.mitre.org/XMLSchema/oval-common-5}CheckEnumeration" default="all" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityStateComplexBaseType", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5")
@XmlSeeAlso({
    EntityStateRecordType.class
})
public abstract class EntityStateComplexBaseType
    extends EntityComplexBaseType
{

    @XmlAttribute(name = "entity_check")
    protected CheckEnumeration entityCheck;

    /**
     * Gets the value of the entityCheck property.
     * 
     * @return
     *     possible object is
     *     {@link CheckEnumeration }
     *     
     */
    public CheckEnumeration getEntityCheck() {
        if (entityCheck == null) {
            return CheckEnumeration.ALL;
        } else {
            return entityCheck;
        }
    }

    /**
     * Sets the value of the entityCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckEnumeration }
     *     
     */
    public void setEntityCheck(CheckEnumeration value) {
        this.entityCheck = value;
    }

}
