//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 01:02:18 PM CET 
//


package com.suse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * The StatesType is a container for one or more state child elements.
 * Each state provides details about specific characteristics that can be used during an evaluation of an object.
 * <p>
 * Please refer to the description of the state element for more information about an individual state.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatesType", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5")
public class StatesType {

    @XmlElement(name = "state", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", required = true)
    protected List<StateType> states;

    /**
     * Gets the contained states.
     */
    public List<StateType> getStates() {
        if (states == null) {
            states = new ArrayList<>();
        }
        return this.states;
    }

}
